language: java
jdk: oraclejdk7

before_install:
  - sudo apt-get install -qq libstdc++6:i386 lib32z1
  - export COMPONENTS=platform-tools,extra-google-m2repository,extra-android-m2repository,android-19,extra-google-google_play_services,extra-android-support,build-tools-19.0.3
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/bf7bee02793a81a0c5ffbf5988a12b43763d8a78/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env
  - mvn install:install-file -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.0.1 -Dpackaging=jar -Dfile="$ANDROID_HOME/extras/android/support/v4/android-support-v4.jar"

install:
  - TERM=dumb ./gradlew assemble

script:
  - TERM=dumb ./gradlew robolectric --info
